[package]
name = "payment-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wire-contracts = { path = "../wire-contracts" }
shared-kernel = { path = "../shared-kernel" }
serde.workspace = true
thiserror.workspace = true
async-trait.workspace = true

[lints]
workspace = true
