syntax = "proto3";

package payment.v1;

service PaymentService {
  rpc AuthorizePayment (AuthorizePaymentRequest) returns (AuthorizePaymentResponse);
  rpc CapturePayment (CapturePaymentRequest) returns (CapturePaymentResponse);
}

message AuthorizePaymentRequest {
  string order_id = 1;
  string customer_id = 2;
  int64 amount_cents = 3;
  string currency = 4;
}

message AuthorizePaymentResponse {
  string payment_id = 1;
  string status = 2;
}

message CapturePaymentRequest {
  string payment_id = 1;
}

message CapturePaymentResponse {
  string payment_id = 1;
  string status = 2;
}
