syntax = "proto3";

package inventory.v1;

service InventoryService {
  rpc ReserveStock (ReserveStockRequest) returns (ReserveStockResponse);
  rpc ReleaseStock (ReleaseStockRequest) returns (ReleaseStockResponse);
}

message ReserveStockRequest {
  string order_id = 1;
  repeated StockItem items = 2;
}

message StockItem {
  string sku_id = 1;
  uint32 quantity = 2;
}

message ReserveStockResponse {
  string reservation_id = 1;
  string status = 2;
}

message ReleaseStockRequest {
  string reservation_id = 1;
}

message ReleaseStockResponse {
  string reservation_id = 1;
  string status = 2;
}
